apiVersion: v1
kind: Service
metadata:
  name: docker-registry
spec:
  selector:
    name: docker-registry
  ports:
  - protocol: TCP
    name: mirror
    port: 5000
    nodePort: {{.Values.docker.hostPort}}
  - protocol: TCP
    name: local
    port: 5001
    nodePort: {{add1 .Values.docker.hostPort}}
  type: NodePort
